import streamlit as st
name=st.text_input("enter your name:")
fname=st.text_input("enter your father name:")
religion=st.text_input("enter your religion:")
adr=st.text_input("enter your address:")
age=st.text_input("enter your age:")
classdata=st.selectbox("enter your class:",("matric","intermediate","Bachelor","Graduation","M.phil","PHD"))
cnic=st.text_input("Enter your CNIC")
email=st.text_input("enter your email:")
phone=st.text_input("enter your phone number:")

button=st.button("Done")
if button:
    st.success("form submitted successfully")
    st.markdown("### student detail")
    st.markdown(f"**name:**{name}")
    st.markdown(f"**father name:**{fname}")   
    st.markdown(f"**religion:**{religion}")   
    st.markdown(f"**age:**{age}")
    st.markdown(f"**class:**{classdata}") 
    st.markdown(f"**cnic:**{cnic}")
    st.markdown(f"**email:**{email}")
    st.markdown(f"**phone:**{phone}")  
else:
    st.warning("please fill all fields")
