import streamlit as st
name=st.text_input("enter your name:")
fname=st.text_input("enter your father name:")
religion=st.text_input("enter your religion:")
adr=st.text_input("enter your address:")
age=st.text_input("enter your age:")
classdata=st.selectbox("enter your class:",("matric","intermediate","Bachelor","Graduation","M.phil","PHD"))
cnic=st.text_input("Enter your CNIC")
email=st.text_input("enter your email:")
phone=st.text_input("enter your phone number:")

button=st.button("Done")
if button:
    st.success("form submitted successfully")
    st.write("### student detail")
    st.write(f**name:**{name}")
    st.write(f*** father name:**{fname}")   
    st.write(f**religion:**{religion}")   
    st.write(f**age:**{age}")
     st.write(f**class:**{classdata}") 
     st.write(f**cnic:**{cnic}")
      st.write(f**email:**{email}")
    st.write(f**phone:**{phone}")  
